quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-3.5-flash
quarkus.langchain4j.ai.gemini.chat-model.log-requests=true
quarkus.langchain4j.ai.gemini.chat-model.log-responses=true

quarkus.langchain4j.embedding-model.provider=dev.langchain4j.model.embedding.onnx.bgesmallenq.BgeSmallEnQuantizedEmbeddingModel
quarkus.langchain4j.pgvector.dimension=384
rag.location=src/main/resources/rag

quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.port=5432
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.packages=dev.langchain4j.quarkus.workshop.entity
